stages:
    - deploy

deploy:
    stage: deploy
    tags:
        - runner-docker-2
    image: alpine:latest
    before_script:
        - apk add --no-cache sshpass openssh-client
    script:
        - |
            sshpass -p "$SSH_PASSWORD" ssh \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -o LogLevel=ERROR \
              buser@"$DEPLOY_HOST" '
              set -e
              cd /home/buser/cg-site/app
              git pull
              docker build -t cg-site .
              docker rm -f cg-site || true
              docker run -d -p 80:80 -p 443:443 \
                -v public:/var/www/html/public/ \
                --network=my-net \
                --env-file ~/cg-site/config/.env.prod.local \
                --name cg-site cg-site
              '
    only:
        - master
