
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "app"
      # Changez le mot de passe en production
      MYSQL_PASSWORD: "!ChangeMe!"
      MYSQL_ROOT_PASSWORD: "!ChangeMeRoot!"
      MYSQL_USER: "app"
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
