name: PushGitlab

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Push To Gitlab
              env:
                  token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
              run: |
                  echo Starting to push repo to gitlab
                  git config user.name "KaiYou"
                  git config user.email "turin-ylan@outlook.fr"
                  git remote set-url origin "https://oauth2:${token}@gitlab.bonnard.io/KaiYou/cg-site.git"
                git pull --rebase https://gitlab.bonnard.io/KaiYou/cg-site.git master
                git push https://gitlab.bonnard.io/KaiYou/cg-site.git master
